<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />
    <title><?php echo $this->escape($this->title) ?></title>
    <?php echo $this->headScripts(null) ?>
</head>
<body>
   
    <div class="container">

        <div class="block">
            <div id="header" class="column span-24">
                <h1>Admin Layout</h1>
            </div>
        </div>

        <div class="block">
            <div id="content" class="column span-16">
               
                <?php echo $this->layout()->content ?>

            </div>

            <div id="content_right" class="column span-7">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
        </div>

        <div class="block">
            <div id="footer" class="span-24">
                <p>kinda copyright &copy; 2008</p>
            </div>
        </div>

    </div>

</body>
</html>
